### ISSUE TITLE
Sort de départ du paladin ne s'affichent pas

### ISSUE THREAD

**Issue by Krabator** [r-e-d/poe-fr#17]
Bonjour,

Avec le patch au 05/09/2015, lors de la création d'un nouveau personnage, la sélection des sorts de paladin ne s'affiche pas correctement.

![creation_paladin_sorts_ko](https://cloud.githubusercontent.com/assets/14138462/9699321/fe54eda0-53de-11e5-86a3-839335e1ef3f.png)

Idem pour leur capacité passive.

![creation_paladin_sorts_ko2](https://cloud.githubusercontent.com/assets/14138462/9699353/6a24ede0-53e0-11e5-8d41-ecc91665380f.png)

**Comment by r-e-d** [comment]
C'est corrigé.

Merci pour le retour.
