### ISSUE TITLE
Une réplique bizarre...

### ISSUE THREAD

**Issue by Krabator** [r-e-d/poe-fr#18]
La réponse 1 ne me semble pas correcte vu que c'est plutot sa soeur qui est venu la trouvée...
A confronter avec la VO... ça me parrait louche

![trad001](https://cloud.githubusercontent.com/assets/14138462/9700617/7038e636-5409-11e5-9695-87306e9b6cee.png)

**Comment by r-e-d** [comment]
C'est corrigé. Merci de l'avoir signalé.
