### ISSUE TITLE
Tout dépend comment vous la comptez la naine

### ISSUE THREAD

**Issue by Krabator** [r-e-d/poe-fr#19]
Mieux : Tout dépend de la façon dont vous comptez la naine

![trad002](https://cloud.githubusercontent.com/assets/14138462/9700980/c109308a-5417-11e5-8b56-da3f374c1166.png)

dites moi si ça vous interesse que je fasse des propositions... j'ai déjà participé à l'amélioration des trad de BG:EE et ID:EE

**Comment by r-e-d** [comment]
J'ai intégré la proposition.

Je suis toujours preneur de corrections ou d'améliorations de la traduction. Toute aide est la bienvenue.

Merci.

**Comment by Krabator** [comment]
ok ben je vais en faire quelques une alors
