### ISSUE TITLE
Suggestions diverses 06/09/2015

### ISSUE THREAD

**Issue by Krabator** [r-e-d/poe-fr#20]
Au lieu de faire un sujet par remarque, je vais faire des grappes de suggestions... sinon je pense qu'on va pas s'en sortir :)

...il y a un coléoptère piquant par ici, qui en est porteur.
Vous irez mieux une fois qu'elle aura passé...
Je pense que l'on parle de "La touche de pourriture grondante" (au passage c'est pas top comme traduction, je trouve que c'est trop litéral, j'aurai mis "la pourriture grondante") donc "elle" ça irait mieux.

![trad003](https://cloud.githubusercontent.com/assets/14138462/9704117/25987dc0-549b-11e5-9ede-9ef78de35b8b.png)

cela calme les entrailles, ça ne sonne pas fr non ?
Je te propose "cela calme les maux de ventre"

![trad004](https://cloud.githubusercontent.com/assets/14138462/9704162/cc20c62e-549c-11e5-801d-42e8be27ae4c.png)

"car cela n'arrive plus de nos jours"... je mettrai ça c'est moins lourd.
![trad005](https://cloud.githubusercontent.com/assets/14138462/9704209/06c47e6e-549e-11e5-9d80-095d18aafbd1.png)

"un citadin sans défense" ...rapport à la définition wikipédia de tenderfoot.
Pied-tendre... c'est vraiment la traduction litérale :)
A tenderfoot is slang for an inexperienced person, particularly one who is not adapted to a rural or outdoor lifestyle setting.
![trad006](https://cloud.githubusercontent.com/assets/14138462/9704234/a594131a-549e-11e5-920a-9eda899aab58.png)

Ce n'est plus aussi grand que ça l'a été, mais ça reste vaste. La terre principale est un continent au nord ouest d'ici et il était d'usage d'inclure Readceras et le Dyrwood parmi ses colonies.
Il y a à peu près cent cinquante ans, le Dyrwood gagna son indépendance vis à vis de l'empire,...
![trad007](https://cloud.githubusercontent.com/assets/14138462/9704293/b3f2c12e-54a1-11e5-9885-3873852acd30.png)

l'affaire de la famille --> l'affaire familiale
![trad008](https://cloud.githubusercontent.com/assets/14138462/9704315/eb32f7f2-54a2-11e5-8290-1fc268c0d3d2.png)

Heodan vient de nous expliquer que le Dyrwood était une ancienne colonie aedyrane...
Je mettrais donc "Le Dyrwood est une ancienne colonie aedyrane" plutot qu'"une sorte"
![trad009](https://cloud.githubusercontent.com/assets/14138462/9704325/71559a7e-54a3-11e5-9566-0120135211f7.png)

Je ne l'ai pas vu depuis... (comme elle ne l'a pas encore vu, cela me semble plus naturel)
![trad010](https://cloud.githubusercontent.com/assets/14138462/9704400/b46eb690-54a5-11e5-8b00-ad39c9e6f4e2.png)

Ma famille voyage elle aussi (Je ne connais pas le verbe "vague")
![trad011](https://cloud.githubusercontent.com/assets/14138462/9704413/2899d8ce-54a6-11e5-8fa0-0c73b3a558a5.png)

J'ai été absente, mais j'ai entendu de drôles de choses récemment. Il semblerait que les gens ont du mal à procréer, beaucoup de gens. Cela dure depuis des années maintenant et d'une certaine façon, cela empire.
![trad012](https://cloud.githubusercontent.com/assets/14138462/9704468/4b5f4c52-54a8-11e5-8630-9c95f97722f1.png)

Le fouetter un peu (c'est dans le sens de le faire avancer plus vite)
![trad013](https://cloud.githubusercontent.com/assets/14138462/9704488/2db4f106-54a9-11e5-9a57-7e7df6205d2f.png)

J'aimerais bien connaitre la VO sur ce passage... la deuxième partie de la traduction a besoin d'un lifting
![trad014](https://cloud.githubusercontent.com/assets/14138462/9704765/1d58fb5a-54b2-11e5-9cbb-a011fa8c466c.png)

En anglais, fangs signifie "crocs"... je pense qu'il faudrait le traduire par "Crocs de Galawain" cela indique bien que cette tribu s'identifie comme le bras armé du dieu Galawain.
![trad015](https://cloud.githubusercontent.com/assets/14138462/9705054/41b24c08-54b8-11e5-810b-ca03361268cc.png)

Les boutons de validation (oui / non) n'apparaissent plus sur l'interface...
![trad016](https://cloud.githubusercontent.com/assets/14138462/9705406/b1155472-54c3-11e5-9cac-763b244d75d7.png)

J'enlèverai "de l'arbre" (la monstruosité noueuse et sans feuille, c'est l'arbre)
![trad017](https://cloud.githubusercontent.com/assets/14138462/9705606/29724e92-54ca-11e5-8fd1-578a5f0e1ebf.png)

A l'instant où ils finissaient (au lieu de Comme ils finissaient)
![trad018](https://cloud.githubusercontent.com/assets/14138462/9705638/85a92522-54cb-11e5-9fcf-c6e736f583b7.png)

**Comment by r-e-d** [comment]
J'ai commencé à intégrer ces suggestions.

Pour tenderfoot, cela ne me semble pas une mauvaise traduction.

Pour le dialogue de Calesca, j'ai laissé 'donner la vie', ce n'est pas le même sens que 'procréer'. En anglais, c'est 'giving birth'.

Pour le passage à revoir, voici le texte en anglais:
"The wind begins to swell, whipping around the camp, electric and volatile, upending pots and rattling tents like an angry spirit.

You can feel it begin to seep beneath your skin, and where it pierces you it feels as though it is rending you apart from within."

Je n'ai pas encore regardé pour la suite.

Pour les boutons n'apparaissant plus, j'ai vu un post à ce sujet sur le forum officiel, j'ai l'impression que c'est un bug du dernier patch.

**Comment by Krabator** [comment]
Pour pied-tendre, rajoute juste un tiret entre pied et tendre alors.

You can feel it begin to seep beneath your skin, and where it pierces you it feels as though it is rending you apart from within.
-->
Vous pouvez le sentir s'insinuer sous votre peau, et lorsqu'il ressort vous avez la sensation qu'il vous déchire de l'intérieur.

Pour la phrase avec donner la vie, ce n'est pas la seule modification que je propose.
En particulier, il y a un "à propos de cela" qui traine alors que la phrase précédente ne fait référence à rien du tout... (c'est le screenshot juste avant)

En règle générale, quand je met tout une phrase en fr, c'est qu'elle comporte des suggestions de modification du début à la fin de la phrase... sinon je ne met que l'extrait.

**Comment by r-e-d** [comment]
J'ai fini l’intégration des suggestions.

Merci.
