### ISSUE TITLE
Dialogue non traduit

### ISSUE THREAD

**Issue by Grouiiik** [r-e-d/poe-fr#24]
Une ligne de dialogue avec Eder n'est pas traduite :
http://tof.canardpc.com/view/095c6567-7d5e-4b40-98fd-e6a29bd2645c.jpg

**Comment by r-e-d** [comment]
C'est corrigé, merci de l'avoir signalé :)

**Comment by Grouiiik** [comment]
Merci pour le très bon boulot que tu accomplis

---

De : Renaud Durlinmailto:notifications@github.com
Envoyé : ‎13/‎03/‎2016 20:44
À : r-e-d/poe-frmailto:poe-fr@noreply.github.com
Cc : Grouiiikmailto:sylvain.gilbert@outlook.com
Objet : Re: [poe-fr] Dialogue non traduit (#24)

C'est corrigé, merci de l'avoir signalé :)

---

**Comment by Grouiiik** [comment]
Bonjour,

J'ai commenté la traduction, il y a une petite erreur d'accord ;)

Date: Sun, 13 Mar 2016 12:44:32 -0700

**Comment by r-e-d** [comment]
En effet, ça devrait être bon maintenant.

**Comment by Grouiiik** [comment]
Merci :)

Date: Mon, 14 Mar 2016 12:54:08 -0700
