### ISSUE TITLE
Maybe missing Token?

### ISSUE THREAD

**Issue by Xaratas** [r-e-d/poe-fr#25]
https://github.com/r-e-d/poe-fr/blob/master/data_expansion1/localized/fr-fixed/text/conversations/px1_02_durgans_battery/px1_02_si_chasm_rescue_redux.stringtable#L714

All languages mention [Specified 0] but not french.

/data_expansion1/localized/en/text/conversations/px1_02_durgans_battery/px1_02_si_chasm_rescue_redux.stringtable ID:      <ID>135</ID>
en: When [Specified 0]'s hand is mere inches away, the outcropping beneath the trapped man's feet suddenly shudders and gives way, and he starts to fall.
de_patch: Als die Hand von [Specified 0] nur noch wenige Zentimeter von dem Mann entfernt ist, bricht der Vorsprung unter dessen Füßen plötzlich zusammen und er beginnt zu fallen.
es: Cuando la mano de [Specified 0] está a pocos centímetros de las suyas, el afloramiento bajo los pies del hombre cruje y cede, y empieza a caer.
it: Quando la mano di [Specified 0] è a pochi centimetri dalla sua, la sporgenza sotto i piedi del poveretto cede di schianto. L'uomo inizia a cadere.
pl: Gdy [Specified 0] już niemal dosięga wieśniaka, występ pod jego stopami niespodziewanie trzęsie się i obsuwa. Mężczyzna zaczyna spadać.
ru: Когда [Specified 0] уже практически дотягивается рукой до мужчины, выступ под ногами несчастного внезапно вздрагивает и начинает вместе с ним падать.
fr: Mais alors que celle-ci se trouve à quelques centimètres, l'affleurement situé sous les pieds de l'homme piégé cède et celui-ci commence à tomber.

**Comment by r-e-d** [comment]
Thanks, I changed the traduction to use [Specified 0].
