### ISSUE TITLE
Pléonasme

### ISSUE THREAD

**Issue by Artames** [r-e-d/poe-fr#26]
Bonjour, 

Je souhaiterais signaler le pléonasme "incessamment sous peu" dans un des premiers dialogues de Urgeat. Je vous propose d'utiliser soit "incessamment" soit "sous peu". Les deux combinés me semblent de trop. A débattre.

![pleonasme](https://cloud.githubusercontent.com/assets/20116263/16317923/f9f3affa-398c-11e6-86d4-5f581d691f99.png)

**Comment by r-e-d** [comment]
Bonjour,

En effet ça fait un peu lourd. Des deux possibilités, je préfère "doit accoucher sous peu.".
