### ISSUE TITLE
Compatibilité avec la 3.04.1165 ?

### ISSUE THREAD

**Issue by elFakir** [r-e-d/poe-fr#27]
Bonjour !  Dans le fichier README.md de la traduction corrigée, la version 3.03.1047 de PoE est mentionnée. Lorsque je lance sur ma machine, j'ai une 3.04.1165, du coup est-ce que je peux quand même utiliser votre travail, ou dois-je rester sur la traduction française fournie par défaut ?  Merci !

**Comment by r-e-d** [comment]
Je viens de faire la mise à jour pour la dernière version.
