### ISSUE TITLE
"Vous avez rejoint ce trou perdu pour rencontrer le célèbre champion de la Baie du défi."

### ISSUE THREAD

**Issue by Bonbadil** [r-e-d/poe-fr#28]
Bonjour,

Cette nième phrase tordue m'a fait chercher de meilleures traductions, et je suis tombé ici. Merci pour cet effort de correction. Je vais l'installer de ce pas.

À l'arrivée dans Dyrwood, au niveau du pont, un garde nous interpelle : https://github.com/r-e-d/poe-fr/blob/master/data/localized/fr-fixed/text/conversations/00_dyrwood/00_cv_bridge_guard.stringtable
Les textes 9 et 10 sont des alternatives au 1 en fonction de la réputation du personnage principal.

Et je les trouve très mal traduit. Pour le 9 :
````The guard sighs with relief as he looks at you. "What are the odds. Stuck in this backwater only to meet the famed champion of Defiance Bay. Berath's Wheel brings mercy today, indeed."````
devient
````Le garde soupire de soulagement en vous voyant. "Alors... Vous avez rejoint ce trou perdu pour rencontrer le célèbre champion de la Baie du défi. La Roue de Berath est bien miséricordieuse aujourd'hui."````

"What are the odds?" devient un simple "Alors..." ?
"Vous avez rejoint ce trou perdu pour rencontrer le célèbre champion de la Baie du défi" Pas besoin que j'aille dans ce trou perdu si c'est pour me rencontrer moi-même...

Mais je ne sais pas trop quoi proposer comme traduction...

**Comment by enwin** [comment]
En effet le sens n'est pas bon.

Un petit essai de traduction pour lancer la discussion :
`Qui aurait pu croire que rester bloqué dans ce trou perdu me permette de rencontrer le célèbre champion de la Baie du défi.`

Ou si l'on souhaite garder la structure :
`Qui l'eut cru. Rester bloqué dans ce trou perdu m'a permis de rencontrer le célèbre champion de la Baie du défi.`

En espérant que cela donne des idées de traduction plus fidèle.

**Comment by Bonbadil** [comment]
Ah, pas mal. Ça m'inspire ceci, pour essayer de coller aux phrases courtes et directes d'un soldat :
`Qui l'eut cru. C'est coincé dans ce trou perdu que je rencontre le célèbre champion de la Baie du défi.`
Je vous laisse trancher. :-)

Et faudra adapter le texte alternatif 10 :
`What are the odds. Stuck in this backwater only to meet a Kind Wayfarer.`
"Kind Wayfarer" a été traduit par "Aimable voyageur". S'ils le disent... Moi, ça ne m'évoque rien mais je rate peut-être une référence.

**Comment by r-e-d** [comment]
Bonjour,

J'ai fait les corrections en utilisant la proposition de Bonbadil.

"Aimable voyageur" c'est un des ordres de Paladins.
